---
- name: Set UMASK to 077 in login.defs
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: "^#?UMASK"
    line: UMASK 077

- name: Set DIR_MODE to 0700 in adduser.conf
  ansible.builtin.lineinfile:
    path: /etc/adduser.conf
    regexp: "^#?DIR_MODE="
    line: DIR_MODE=0700

- name: Make private directories private
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop: "{{ private_dirs }}"

- name: Set correct hostname in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127\\.0\\.1\\.1( |\t)"
    line: "127.0.1.1\t{{ ansible_hostname }}"

- name: OpenSSH server configuration
  block:
    - name: Set sshd_config recommended options
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?{{ item.name }}"
        line: "{{ item.name }} {{ item.value }}"
      loop:
        - { name: PermitRootLogin, value: "no" }
        - { name: HostbasedAuthentication, value: "no" }
        - { name: PermitEmptyPasswords, value: "no" }
      notify: Restart the ssh service

    - name: In sshd_config, set AddressFamily to inet (i.e. IPv4 only)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?AddressFamily"
        line: AddressFamily inet
      when: sshd_addressfamily_inet
      notify: Restart the ssh service

    - name: In sshd_config, disable PasswordAuthentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: PasswordAuthentication no
      when: sshd_disable_psw_auth
      notify: Restart the ssh service

    - name: Force all notified handlers to run at this point
      ansible.builtin.meta: flush_handlers

- name: Prevent setting NTP server from DHCP (with systemd-timesyncd)
  block:
    - name: Delete timesyncd dhclient hook
      ansible.builtin.file:
        path: /etc/dhcp/dhclient-exit-hooks.d/timesyncd
        state: absent

    - name: Delete timesyncd runtime config generated from dhclient hook
      ansible.builtin.file:
        path: /run/systemd/timesyncd.conf.d/01-dhclient.conf
        state: absent
      notify: Restart timesyncd

    - name: Force all notified handlers to run at this point
      ansible.builtin.meta: flush_handlers

- name: Sysctl parameters
  block:
    - name: Set IPv4-related sysctl parameters
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        reload: false
      loop:
        - { name: net.ipv4.conf.all.send_redirects, value: "0" }
        - { name: net.ipv4.conf.default.send_redirects, value: "0" }
        - { name: net.ipv4.conf.all.accept_source_route, value: "0" }
        - { name: net.ipv4.conf.default.accept_source_route, value: "0" }
        - { name: net.ipv4.conf.all.accept_redirects, value: "0" }
        - { name: net.ipv4.conf.default.accept_redirects, value: "0" }
        - { name: net.ipv4.conf.all.log_martians, value: "1" }
        - { name: net.ipv4.conf.default.log_martians, value: "1" }
        - { name: net.ipv4.icmp_echo_ignore_broadcasts, value: "1" }
        - { name: net.ipv4.conf.all.rp_filter, value: "1" }
        - { name: net.ipv4.conf.default.rp_filter, value: "1" }
      notify: Reload the sysctl configuration

    - name: Set IPv6-related sysctl parameters
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        reload: false
      loop:
        - { name: net.ipv6.conf.all.accept_ra, value: "0" }
        - { name: net.ipv6.conf.default.accept_ra, value: "0" }
        - { name: net.ipv6.conf.all.accept_redirects, value: "0" }
        - { name: net.ipv6.conf.default.accept_redirects, value: "0" }
      notify: Reload the sysctl configuration

    - name: Force all notified handlers to run at this point
      ansible.builtin.meta: flush_handlers

- name: Disable IPv6
  ansible.builtin.include_role: { name: dmotte.disable_ipv6 }
  vars:
    disable_ipv6_reload_sysctl_if_changed: "{{ reload_sysctl_if_changed }}"
  when: disable_ipv6

- name: Force all notified handlers to run at this point
  ansible.builtin.meta: flush_handlers
