---
- name: Restart the ssh service
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: Reload the sysctl configuration
  # We have to use the command here because (to date) the
  # ansible.posix.sysctl module does not allow to force a reload
  ansible.builtin.command:
    cmd: sysctl --system
